### ISSUE TITLE
Ensure all ObjectStores have publicly available client

### ISSUE THREAD

**Issue by wjones127** [influxdata/object_store_rs#10]
ObjectStores might want to be extended with additional traits that use the underlying client. For example, in delta-rs we would want to extend the client to implement a version of rename that failed if the destination already exists (see delta-io/delta-rs#610).

`AmazonS3` does expose a method `.client()`:

https://github.com/influxdata/object_store_rs/blob/5f488c5ce8c8c12eea3bd068d61308ae95e1c458/src/aws.rs#L533-L535

`MicrosoftAzure` only has a **private** field `container_client`:

https://github.com/influxdata/object_store_rs/blob/5f488c5ce8c8c12eea3bd068d61308ae95e1c458/src/azure.rs#L73-L74

`GoogleCloudStorage` only has a **private** field `client`:

https://github.com/influxdata/object_store_rs/blob/5f488c5ce8c8c12eea3bd068d61308ae95e1c458/src/gcp.rs#L103-L104

They all will return a different type, but maybe we should implement for each a `client()` method like the S3 has?

**Comment by tustvold** [comment]
I'm a bit wary of exposing the clients used internally as I suspect we may want to change these down the line. Both Rusoto and cloud_storage are not official crates, with somewhat patchy support.

Perhaps we could add copy support directly to the trait, it seems like a reasonable addition to me?

**Comment by wjones127** [comment]
> Perhaps we could add copy support directly to the trait, it seems like a reasonable addition to me?

As in, copy the client rather than returning a reference / shared pointer?

> I'm a bit wary of exposing the clients used internally as I suspect we may want to change these down the line. 

Yeah, I agree. The alternative would be crates should bring their object store extensions into this crate as optional features. So delta-rs would bring in the `rename_noreplace()` method as an optional trait. In the S3 case, that might mean bringing over [dynamodb lock](https://github.com/delta-io/delta-rs/tree/main/dynamodb_lock), which may be more than you wish to accept (or maybe not!).

Or even a final alternative would be that in delta-rs we wrap the `ObjectStore` implementors instead of using them directly.

**Comment by tustvold** [comment]
> As in, copy the client rather than returning a reference / shared pointer?

I meant adding `CopyObject` support to `ObjectStore` itself.

> The alternative would be crates should bring their object store extensions into this crate as optional features

I think an optional feature that adds CreateIfNotExists and CopyIfNotExists operations would be really cool. It's a real pain that S3 doesn't natively support it, and if we can somehow hide that from users that would be awesome.

**Comment by roeap** [comment]
In case of Adls Gen2 the *IfNotExist methods are natively supported. In delta-rs we also have an implementation for local file systems, which only on windows needs some extra care - I think... for blob and S3 afaik some external service is needed.

I'd be happy to contribute adls gen2 to this crate 🙂.

**Comment by wjones127** [comment]
> I meant adding CopyObject support to ObjectStore itself. A rename is just a copy followed by a delete.

Sounds good. I've started implementing that in #14. I will close #11.
