### ISSUE TITLE
Move Away From SDKs

### ISSUE THREAD

**Issue by tustvold** [influxdata/object_store_rs#18]
**Problem**

Currently this crate uses upstream crates to provide interaction with object storage. This comes with a few downsides:

* Missing features, e.g. range support, conditionals, etc...
* Inconsistent error handling, e.g. it can be next to impossible to get the HTTP status code
* Extreme dependency bloat

**Proposal**

This crate does not intend to cover more than the basic APIs of each store, which boils down to just a couple of different request types. I would like therefore like to propose:

* Move to using a reqwest client directly
* Use serde to serialize payloads
* Use ring to handle signatures/etc...
* Use rustls to handle TLS

This will allow:

* Consistent error handling, retries, etc...
* Smaller dependency footprint
* New features without waiting on upstreams
* Simpler codebase

It's up to whoever picks this up where to start, but I would suggest starting with GCS as:

* It will unlock range requests
* The authentication logic is simpler than say AWS
* The JSON API is relatively straightforward

If that goes well, we can then look to move onto the others

**Additional Context**

https://github.com/influxdata/object_store_rs/pull/15#issuecomment-1134893330

**Comment by wjones127** [comment]
The main downside of not using SDKs is we need to implement the credential/authentication handling ourselves. For example, in AWS supporting environment variables, assuming roles, SSO profiles, and so on. I know in delta-rs (where we have been using our own object store implementation) a large portion of feature requests are around allowing different authentication mechanisms. Unfortunately, even [aws-config](https://crates.io/crates/aws-config/0.14.0/dependencies) has quite a few dependencies.

**Comment by tustvold** [comment]
I agree that there is some non-trivial implementation work to be done there, however, I would also wager that support for the full suite of AWS profiles is not something we necessarily need. Much of the functionality, e.g. MFA, SSO, etc... does not make all that much sense in a non-interactive context, and in an interactive context you can just use the existing CLI tools to generate the credentials or something like [aws-vault](https://github.com/99designs/aws-vault) or [awsudo](https://github.com/makethunder/awsudo)

**Comment by wjones127** [comment]
> I would also wager that support for the full suite of AWS profiles is not something we necessarily need. Much of the functionality, e.g. MFA, SSO, etc... does not make all that much sense in a non-interactive context

We actually get quite a bit of users who are in an interactive context for delta-rs Python bindings. And I suspect there will be other cases.

But I think I take your point there are decent escape hatches, so even if we only support the most environment variables users will have workarounds to export those from more advanced auth methods.

**Comment by alamb** [comment]
Moved to arrow: https://github.com/apache/arrow-rs/issues/2176
