### ISSUE TITLE
Implement copy_if_not_exists for AWS

### ISSUE THREAD

**Issue by wjones127** [influxdata/object_store_rs#23]
`copy_if_not_exists` is not implementable in S3 without some external lock. Hence delta-rs created [dynamodb-lock](https://github.com/delta-io/delta-rs/tree/main/dynamodb_lock). We should aim to implement this method with an optional feature that includes dynamodb-lock. How to configure the lock client is an open question.

**Comment by alamb** [comment]
Ported to arrow: https://github.com/apache/arrow-rs/issues/2179
