### ISSUE TITLE
Support assuming roles directly when using AWS S3

### ISSUE THREAD

**Issue by timvw** [influxdata/object_store_rs#31]
Users have an expectation that a correctly configured AWS credentials or profile file will cause systems to assume configured roles. Unfortunately Rusoto does not do this out of the box ([issue](https://github.com/rusoto/rusoto/issues/1758), [pr](https://github.com/rusoto/rusoto/pull/1842)).

One possible way to mitigate this is by migrating to [aws-sdk-rust](https://github.com/awslabs/aws-sdk-rust), but does not seem compatible with #18 .

**Comment by timvw** [comment]
Started working on an implementation using aws-sdk-rust: https://github.com/timvw/object_store_rs/tree/feat-awssdk

**Comment by alamb** [comment]
Ported to arrow: https://github.com/apache/arrow-rs/issues/2178
