### ISSUE TITLE
Remove next_token from ListResult

### ISSUE THREAD

**Issue by timvw** [influxdata/object_store_rs#35]
ListResult has next_token: Option<String> (Token passed to the API for the next page of list results) 
ObjectStore has nowhere a method that accepts such token, thus no idea why this is part of the API.

fn list: List all the objects with the given prefix

fn list_with_delimiter: List objects with the given prefix and an implementation specific delimiter. 
-> Should all such objects be returned? Or only some? (And how many? Leave it to underlying impl?)

**Comment by wjones127** [comment]
`list()` returns a `BoxStream<ObjectMeta>`, so maybe we should simply change `list_with_delimiter` to do the same? Except that `list_with_delimiter` is also providing `common_prefixes: Vec<Path>`. So maybe `BoxStream<ListResult>` is appropriate?

**Comment by roeap** [comment]
The azure SDK does something that might apply here. Essentially list_paths over there returns a stream of `ListPathResponse` objects. Internally this object handles continuation when its polled via a `Pageable` trait.

For convenience it also defines an `Iterator<>` which iterates over the internal list of paths. Maybe we could do something similar here?

https://github.com/Azure/azure-sdk-for-rust/blob/main/sdk/storage_datalake/src/operations/path_list.rs

**Comment by tustvold** [comment]
I think this is an accidental holdover from a previous iteration of the API, I would support removing it
