### ISSUE TITLE
Propose donating object_store_rs to Apache Arrow project 

### ISSUE THREAD

**Issue by alamb** [influxdata/object_store_rs#41]
TDLR I would like to propose donating this project to the Apache Arrow project https://arrow.apache.org/ 

# Rationale
1. A common, high quality object store abstraction for communicating with various remote object stores is useful for a range of projects and usecases. 
2. A library with a common API to access remote object stores is directly aligned with the Arrow mission of providing building blocks for modern high performance analytics systems
1.  The clear governance of Apache Arrow offers the best chance to build a unified and strong community around this crate, hopefully both increasing its adoption and attracting community contributions for its long term evolution and maintenance

# Background
Object stores are increasing important for analytic systems as more data is located in such systems; @yjshen donated an [object store abstraction](https://github.com/apache/arrow-datafusion/pull/950) to  [Arrow Datafusion](https://github.com/apache/arrow-datafusion) to allow Datafusion to read from local files, S3, hdfs, and others.  In https://github.com/apache/arrow-datafusion/issues/2489 the DataFusion community is proposing migrating from this original object store abstraction, part of the DataFusion project (part of apache arrow) to the code in this crate. 

# Provenance
The code in this crate was originally developed by InfluxData, largely by @carols10cents,  for [InfluxDB IOx](https://github.com/influxdata/influxdb_iox). @tustvold  has since extracted the code and released it as its own crate. Upon consideration, as described above, for the long term health of both this code and the `arrow-rs` and `arrow-datafusion` projects, moving it to be an official part of Arrow would be beneficial and we would like to donate it to the community

There is additional background here https://github.com/apache/arrow-datafusion/pull/2677#issuecomment-1167893169

This ticket hopefully can serve as a discussion on the form this donation can take. Some options:
1. Move code into the arrow-datafusion repository
2. Move code into the arrow-rs repository
3. Move code to an apache/arrow-object-store-rs repository
4. Move code to datafusion-contrib

**Comment by tustvold** [comment]
My preference would be for 2 or 3, so that we can potentially provide batteries included APIs within arrow-rs for interacting with object stores (behind a feature gate)

**Comment by rdettai** [comment]
I would be more incline to 1 or 2. I think that 3 creates an unnecessary increase of the number of interconnected repos.

Thanks a lot for the donation!

**Comment by alamb** [comment]
The mailing list discussion and this topic seem to be positive so far -- I will propose a formal vote and figure out the IP clearance process in the next few days

**Comment by alamb** [comment]
This proposal seems to have community support -- I have filed https://github.com/apache/arrow-rs/issues/2030 to track the work to do so (including official acceptance and IP clearance). Closing this issue for now and will track future work in https://github.com/apache/arrow-rs/issues/2030

Thank you all for your comments
