### ISSUE TITLE
Flaky test aws::tests::s3_test

### ISSUE THREAD

**Issue by mkmik** [influxdata/object_store_rs#50]
main was green but now fails with:

```
failures:

---- aws::tests::s3_test stdout ----
thread 'aws::tests::s3_test' panicked at 'assertion failed: `(left == right)`
  left: `[Path { raw: "a/b/c/foo.file" }]`,
 right: `[Path { raw: "a/b%2Fc/foo.file" }]`', src/lib.rs:411:9
stack backtrace:
```

The test is either flaky (with low chance to pass) or depends on some external state which changed after the root cause got merged.

https://app.circleci.com/pipelines/github/influxdata/object_store_rs/169/workflows/18a945aa-947b-4cd3-aeaf-80aa66530648/jobs/1009

https://app.circleci.com/pipelines/github/influxdata/object_store_rs/171/workflows/b5e5dfed-3272-4074-b9ae-8e95be60d12d/jobs/999

**Comment by mkmik** [comment]
I guess this means we don't pin the versions of all the tools we run in the tests?

**Comment by tustvold** [comment]
Nope :sweat_smile: - https://github.com/influxdata/object_store_rs/blob/main/.circleci/config.yml#L178

**Comment by mkmik** [comment]
<img width="365" alt="image" src="https://user-images.githubusercontent.com/52673/178595808-e4df7994-7bda-47f8-aa24-0fafa5097eb3.png">

**Comment by mkmik** [comment]
Last green build was `3d ago`

**Comment by mkmik** [comment]
I'll pin and setup some automation to update the pin independently

**Comment by mkmik** [comment]
pinning to the previous version of localstack worked (and we merged https://github.com/influxdata/object_store_rs/pull/48)

**Comment by alamb** [comment]
Closing for now as this doesn't seem to be actionable anymore and we have moved the code to arrow-rs
