### ISSUE TITLE
AsyncWrite over multi-part upload

### ISSUE THREAD

**Issue by wjones127** [influxdata/object_store_rs#9]
One idea I was exploring in https://github.com/datafusion-contrib/datafusion-objectstore-s3/pull/54 was implementing the `AsyncWrite` trait as an abstraction over multi-part upload. Does that seem like an agreeable addition to this crate?

Multi-part uploads are helpful when uploading large files. For example, you can write parquet files one row group at a time, uploading each row groups data as a part (though more likely there is some buffering in between to get good part sizes). This is the approach taken in Arrow C++ S3 FileSystem. In fact, if we could even upload parts in parallel for better throughput in some scenarios (something [AWS recommends](https://docs.aws.amazon.com/AmazonS3/latest/userguide/mpuoverview.html)).

It seems that GCS supports this through their S3-compatible API ([docs](https://cloud.google.com/storage/docs/multipart-uploads)) and Azure Blob store has some notion of "block blobs" that might be applicable ([docs](https://docs.microsoft.com/en-us/rest/api/storageservices/understanding-block-blobs--append-blobs--and-page-blobs)).

**Comment by domodwyer** [comment]
I'm also hoping the object store can support streaming uploads for exactly the same use case you describe @wjones127 :+1:

I am hoping to dedicate some time to implementing some form of streaming writes in the future, but truthfully  it is not high on my TODO list - I'd be happy if someone beats me to it!

**Comment by alamb** [comment]
Related: https://github.com/influxdata/influxdb_iox/pull/4649

**Comment by alamb** [comment]
I think this was done in https://github.com/apache/arrow-rs/pull/2147 @wjones127 

Let me know if there is something this issue is still tracking.
